import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import OpenAI from 'openai';
import crypto from 'node:crypto';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const port = Number(process.env.PORT || 3001);
const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';

const openai = process.env.OPENAI_API_KEY
  ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
  : null;

const sessions = new Map();

const MIN_QUESTIONS_BEFORE_GUESS = 7;
const MAX_QUESTIONS_BEFORE_GUESS = 10;
const QUESTIONS_AFTER_REJECTED_GUESS = 2;

const ARAB_CELEBRITIES = [
  // ====================== رياضة (170 اسم) ======================
  'محمد صلاح',
  'ياسر القحطاني',
  'سامي الجابر',
  'عمر عبد الرحمن',
  'أسامة هوساوي',
  'نواف العابد',
  'يوسف السالم',
  'ماجد عبد الله',
  'فهد المولد',
  'سالم الدوسري',
  'رونالدينيو (محمد)',
  'علي دائي',
  'رياض محرز',
  'حكيم زياش',
  'أشرف حكيمي',
  'أسامة دراجي',
  'عنتر يحيى',
  'محمود الخطيب',
  'محمد أبو تريكة',
  'أحمد حسن',
  'حسام حسن',
  'إبراهيم حسن',
  'عمرو زكي',
  'ميدو',
  'أحمد فتحي',
  'عبد الله السعيد',
  'محمد النني',
  'رمضان صبحي',
  'مصطفى محمد',
  'عمر مرموش',
  'محمد عبد المنعم',
  'أحمد حجازي',
  'علي جبر',
  'سام مرسي',
  'مروان محسن',
  'محمود عبد الرازق شيكابالا',
  'عبد الله السعيد',
  'طارق حامد',
  'محمد الشناوي',
  'أحمد الشناوي',
  'شريف إكرامي',
  'عصام الحضري',
  'نادر السيد',
  'محمد بركات',
  'محمد زيدان',
  'أحمد عيد عبد الملك',
  'حسام غالي',
  'عمرو السولية',
  'أحمد فتحي',
  'سعد سمير',
  'رامي ربيعة',
  'أيمن أشرف',
  'محمد عبد الشافي',
  'أحمد المحمدي',
  'أحمد عادل',
  'محمد صبحي',
  'ناصر الشمراني',
  'محمد نور',
  'تيسير الجاسم',
  'عبد الله معاذ',
  'ياسر الشهراني',
  'محمد العويس',
  'عمر هوساوي',
  'مبمبي',
  'عبد الله السديري',
  'سعد آل حريث',
  'خالد الغامدي',
  'فهد الهريفي',
  'يوسف الثنيان',
  'حمزة إدريس',
  'عبد الله جمعان الدوسري',
  'محمد كنو',
  'عبد الإله المالكي',
  'سامي النجعي',
  'عبد الله الحمدان',
  'فراس البريكان',
  'صالح الشهري',
  'علي البليهي',
  'حسن كادش',
  'ناصر الدوسري',
  'عبد الرحمن العبيد',
  'عبد الله الخيبري',
  'أيمن يحيى',
  'عبد الرحمن غريب',
  'مارسيلو غروهي',
  'نواف العقيدي',
  'أمير كردي',
  'زيدان إقبال',
  'مصعب الجوير',
  'عبد الله رديف',
  'حامد الغامدي',
  'محمد مران',
  'فهد الرشيدي',
  'سلطان الغنام',
  'مطلق المطيري',
  'أحمد بامسعود',
  'خالد الشافعي',
  'عبد الله الفريدي',
  'علي لاجامي',
  'فيصل الغامدي',
  'تركي العمار',
  'أيمن فتيني',
  'أكرم عفيف',
  'بوعلي',
  'حسن الهيدوس',
  'سعد الشيب',
  'مشعل برشم',
  'باسم الراوي',
  'إسماعيل محمد',
  'علي أسد',
  'حمد إسماعيل',
  'مصطفى طارق',
  'عبد العزيز حاتم',
  'محمد مونتاري',
  'أنس عراب',
  'همام الأمين',
  'علي محمود',
  'رودريغو مورينو',
  'يونس محمود',
  'هوار ملا محمد',
  'نشأت أكرم',
  'علي رضا',
  'بشار رسن',
  'أمجد راضي',
  'أحمد راضي',
  'عدنان درجال',
  'حسين سعيد',
  'فلاح حسن',
  'علاء عبد الزهرة',
  'مهدي كريم',
  'جاسم محمد',
  'علاء حبيل',
  'فرج فاهم',
  'محمود المنيسي',
  'محمد عطية',
  'أحمد الزنكي',
  'محمد الرفاعي',
  'عمر الردادي',
  'خالد بوطيب',
  'مروان الشماخ',
  'حسين خرجة',
  'نور الدين أمرابط',
  'حكيم زياش',
  'أشرف حكيمي',
  'سفيان أمرابط',
  'عز الدين أوناحي',
  'يوسف النصيري',
  'مهدي بن عطية',
  'مبارك بوصوفة',
  'طارق السكتيوي',
  'أسامة دراجي',
  'رياض بودبوز',
  'عبد المؤمن جابو',
  'إسلام سليماني',
  'يوسف بلايلي',
  'رياض محرز',
  'رامي بن سبعيني',
  'إسماعيل بن ناصر',
  'نبيل بن طالب',
  'فوزي غلام',
  'أيمن محيوس',
  'محمد أمين زغبة',
  'مهند جبرين',
  'محمود مرسي',

  // ====================== فن (400 اسم) ======================
  'عادل إمام',
  'كاظم الساهر',
  'نانسي عجرم',
  'تامر حسني',
  'أحلام',
  'شيرين عبد الوهاب',
  'عمرو دياب',
  'عبد الحليم حافظ',
  'محمد عبده',
  'يحيى شاهين',
  'سميرة أحمد',
  'محمود ياسين',
  'نادية الجندي',
  'ليلى علوي',
  'إلهام شاهين',
  'يوسف شعبان',
  'صلاح السعدني',
  'نبيلة عبيد',
  'أحمد حلمي',
  'منى زكي',
  'هند صبري',
  'ظافر العابدين',
  'أصالة نصري',
  'إليسا',
  'ميريام فارس',
  'هيفاء وهبي',
  'نوال الكويتية',
  'بلقيس فتحي',
  'أروى',
  'فهد الكبيسي',
  'محمد منير',
  'لطفي بوشناق',
  'صابر الرباعي',
  'جورج وسوف',
  'وائل كفوري',
  'راغب علامة',
  'ماجدة الرومي',
  'كارول سماحة',
  'ديانا حداد',
  'سعد لمجرد',
  'حاتم عمور',
  'دنيا بطمة',
  'زينة',
  'مي عز الدين',
  'ياسمين عبد العزيز',
  'أمير كرارة',
  'محمد رمضان',
  'كريم عبد العزيز',
  'أحمد عز',
  'هاني سلامة',
  'أحمد السقا',
  'غادة عادل',
  'بوسي',
  'شادية',
  'سعاد حسني',
  'فؤاد المهندس',
  'عبد المنعم مدبولي',
  'سمير غانم',
  'محمد نجم',
  'نجيب الريحاني',
  'إسماعيل ياسين',
  'فريد شوقي',
  'محمود المليجي',
  'زكي رستم',
  'رشدي أباظة',
  'عماد حمدي',
  'حسين رياض',
  'أنور وجدي',
  'محسن سرحان',
  'كمال الشناوي',
  'شكري سرحان',
  'نور الشريف',
  'محمود عبد العزيز',
  'جميل راتب',
  'أحمد زكي',
  'عمر الشريف',
  'صلاح ذو الفقار',
  'حسن يوسف',
  'حسين فهمي',
  'ممدوح وافي',
  'محمد صبحي',
  'علاء ولي الدين',
  'محمد هنيدي',
  'أشرف عبد الباقي',
  'ماجد الكدواني',
  'بيومي فؤاد',
  'سامح حسين',
  'شيكو',
  'هشام ماجد',
  'أحمد فهمي',
  'أكرم حسني',
  'محمد سلام',
  'مصطفى خاطر',
  'حمدي الميرغني',
  'محمد عبد الرحمن',
  'علي ربيع',
  'محمد ثروت',
  'سليمان عيد',
  'لطفي لبيب',
  'إنتصار',
  'سوسن بدر',
  'رجاء الجداوي',
  'ماجدة زكي',
  'بشرى',
  'نيللي كريم',
  'روجينا',
  'درة',
  'أروى جودة',
  'حلا شيحة',
  'ناهد السباعي',
  'جميلة عوض',
  'أمينة خليل',
  'شيرين رضا',
  'إيمان العاصي',
  'ريهام عبد الغفور',
  'ريهام حجاج',
  'منة شلبي',
  'ناهد رشدي',
  'مريم فخر الدين',
  'فاتن حمامة',
  'ماجدة',
  'لبنى عبد العزيز',
  'نعيمة عاكف',
  'هدى سلطان',
  'برلنتي عبد الحميد',
  'سهير رمزي',
  'ميرفت أمين',
  'نيللي',
  'بوسي شلبي',
  'لقاء الخميسي',
  'داليا مصطفى',
  'أيتن عامر',
  'مي كساب',
  'دنيا سمير غانم',
  'إيمي سمير غانم',
  'هيدي كرم',
  'وفاء عامر',
  'صفاء أبو السعود',
  'سهير البابلي',
  'ليلى طاهر',
  'كريمة مختار',
  'أمينة رزق',
  'سناء جميل',
  'عايدة رياض',
  'سميحة أيوب',
  'فردوس عبد الحميد',
  'ليلى فوزي',
  'راقية إبراهيم',
  'زبيدة ثروت',
  'مها صبري',
  'نادية لطفي',
  'سهير رمزي',
  'ناهد شريف',
  'شمس البارودي',
  'سماح أنور',
  'نرمين الفقي',
  'غادة نافع',
  'وفاء مكي',
  'أحمد مكي',
  'أحمد آدم',
  'حسن حسني',
  'سعيد صالح',
  'محمد رضا',
  'أحمد راتب',
  'عبد الله فرغلي',
  'مظهر أبو النجا',
  'أبو بكر عزت',
  'محمد وفيق',
  'محمد الشرقاوي',
  'مصطفى متولي',
  'فاروق الفيشاوي',
  'محمد رياض',
  'خالد الصاوي',
  'عمرو سعد',
  'أحمد فلوكس',
  'أحمد بدير',
  'أشرف زكي',
  'أحمد ماهر',
  'حسن مصطفى',
  'سيد زيان',
  'فكري أباظة',
  'محمود الجندي',
  'سامي العدل',
  'طارق لطفي',
  'أحمد خليل',
  'محمد لطفي',
  'مصطفى شعبان',
  'أحمد صفوت',
  'أحمد زاهر',
  'أحمد حاتم',
  'أحمد داود',
  'آسر ياسين',
  'خالد النبوي',
  'شريف منير',
  'إياد نصار',
  'عمرو يوسف',
  'محمود حميدة',
  'خالد أبو النجا',
  'محمد فراج',
  'أحمد مجدي',
  'أحمد الفيشاوي',
  'رانيا يوسف',
  'صابرين',
  'لبنى ونس',
  'هالة صدقي',
  'أحمد بدير',
  'سوسن بدر',
  'إيمان البحر درويش',
  'علي الحجار',
  'هاني شاكر',
  'مدحت صالح',
  'علاء عبد الخالق',
  'محمد الحلو',
  'هشام عباس',
  'حميد الشاعري',
  'عمرو مصطفى',
  'نادر زكي',
  'أحمد عدوية',
  'محمود العسيلي',
  'أبو الليف',
  'حكيم',
  'شعبان عبد الرحيم',
  'محمد فؤاد',
  'حمادة هلال',
  'أحمد سعد',
  'سامر زين',
  'ماهر زين',
  'حمزة نمرة',
  'أمينة',
  'روبي',
  'سمية الخشاب',
  'لوسي',
  'بسمة بوسيل',
  'مايا دياب',
  'نيكول سابا',
  'باسكال مشعلاني',
  'نوال الزغبي',
  'أمل حجازي',
  'هيفاء حسين',
  'مادلين مطر',
  'جوليا بطرس',
  'عاصي الحلاني',
  'مروان خوري',
  'ملحم زين',
  'زياد برجي',
  'رامي عياش',
  'فضل شاكر',
  'ميشال قزي',
  'زياد الرحباني',
  'مارسيل خليفة',
  'إبراهيم الحكمي',
  'عبد الله الرويشد',
  'نبيل شعيل',
  'مطرف المطرف',
  'عبد الكريم عبد القادر',
  'علي عبد الله',
  'خالد عبد الرحمن',
  'رابح صقر',
  'طلال مداح',
  'أبو بكر سالم',
  'محمد عمر',
  'عبد العزيز المنصور',
  'عبد اللطيف الكويتي',
  'حسن جاسم',
  'داود الكويتي',
  'سعود الراشد',
  'أحمد الجميري',
  'عيسى المرزوق',
  'أحمد الهرمي',
  'إبراهيم جمعة',
  'سلمان العماري',
  'عبد الله بالخير',
  'صادق عبد الله',
  'عباس إبراهيم',
  'محمد عبد الله الفيصل',
  'سامي هلال',
  'علي الشريف',
  'محمد البكر',
  'عبد القادر المهنا',
  'محمد الحجاب',
  'ناصر الصالح',
  'عبد الرحمن العتيبي',
  'عبد الله السبع',
  'بدر بن عبد المحسن',
  'محمد الأحمد',
  'عبد الله الفيصل',
  'خالد الفيصل',
  'سعود بن عبد الله',
  'تركي الميزاني',
  'مساعد الرشيدي',
  'مبارك المانع',
  'فايز المالكي',
  'عبد الإله السناني',
  'محمد الخويطر',
  'عبد الرحمن الخميس',
  'عبد العزيز العلي',
  'محمد القحطاني',
  'ماجد الرشيدي',
  'نواف الصباح',
  'عبد الله العلي',
  'حسين الشريف',
  'محمد الرفاعي',
  'عبد الله الغامدي',
  'سعد الفهد',
  'عبد العزيز المعجل',
  'محمد السالم',
  'عبد الله الحجي',
  'فهد الناصر',
  'بدر الغريب',
  'عبد الله القعود',
  'فهد بن سعيد',
  'محمد السهلي',
  'عبد العزيز الفهد',
  'نايف البقمي',
  'عبد الله الدوسري',
  'محمد المطيري',
  'فهد الفهد',
  'عبد العزيز الدخيل',
  'محمد الزلام',
  'عبد الله البراهيم',
  'فهد الدوسري',
  'عبد الرحمن الحمود',
  'محمد الملا',
  'عبد الله العطوي',
  'فهد العلي',
  'عبد العزيز السليم',
  'محمد الغامدي',
  'عبد الله اليامي',
  'فهد السليم',
  'عبد الرحمن المطيري',
  'محمد الزهراني',
  'عبد الله السبيعي',
  'فهد الرشيد',
  'عبد العزيز العتيبي',
  'محمد الحملي',
  'عبد الله الخالدي',
  'فهد الشمري',
  'عبد الرحمن العنزي',
  'محمد الشمراني',
  'عبد الله الحربي',
  'فهد الغامدي',
  'عبد العزيز الزهراني',
  'محمد الدوسري',
  'عبد الله المالكي',
  'فهد الشهري',
  'عبد الرحمن القرني',
  'محمد البقمي',
  'عبد الله الثويني',
  'فهد العتيبي',
  'عبد العزيز المطيري',
  'محمد السبيعي',
  'عبد الله المري',
  'فهد الدوسري',
  'عبد الرحمن الشهراني',
  'محمد العتيبي',
  'عبد الله القحطاني',
  'فهد الزهراني',
  'عبد العزيز العنزي',
  'محمد الحربي',
  'عبد الله الشهري',

  // ====================== علم (100 اسم) ======================
  'أحمد زويل',
  'علي مصطفى مشرفة',
  'سميرة موسى',
  'ابن الهيثم',
  'الخوارزمي',
  'ابن سينا',
  'زينب الكواري',
  'حياة سندي',
  'فاروق الباز',
  'مجدي يعقوب',
  'نبيل غياث',
  'ابن النفيس',
  'جابر بن حيان',
  'ابن رشد',
  'ابن بطوطة',
  'ابن خلدون',
  'البيروني',
  'الفارابي',
  'الزهراوي',
  'ابن زهر',
  'ابن البيطار',
  'ابن ماجة',
  'ابن حزم',
  'ابن تيمية',
  'ابن القيم',
  'الغزالي',
  'الرازي',
  'الكندي',
  'البتاني',
  'ابن الشاطر',
  'ابن يونس',
  'ابن الهيثم',
  'عبد السلام',
  'محمد عبد السلام',
  'علي جمعة',
  'أحمد مستجير',
  'مصطفى السيد',
  'سمير صادق',
  'إبراهيم شحاتة',
  'عبد المنعم الشرقاوي',
  'ماجد أبو زهرة',
  'نبيل حلمي',
  'أحمد شوقي',
  'محمد عوض',
  'علي الزعبي',
  'غازي القصيبي',
  'سلمان العودة',
  'عائض القرني',
  'محمد العريفي',
  'طارق السويدان',
  'أحمد السيد',
  'محمود السيد',
  'سليمان الخطاف',
  'عبد العزيز بن باز',
  'محمد بن صالح العثيمين',
  'عبد الله بن جبرين',
  'صالح الفوزان',
  'عبد الكريم الخطيب',
  'محمد الغزالي',
  'يوسف القرضاوي',
  'محمد متولي الشعراوي',
  'علي الطنطاوي',
  'محمد رشيد رضا',
  'جمال الدين الأفغاني',
  'محمد عبده',
  'عبد الرحمن الكواكبي',
  'رفاعة الطهطاوي',
  'سليمان الحكيم',
  'أحمد زكي',
  'مصطفى محمود',
  'زغلول النجار',
  'أحمد بهاء الدين',
  'محمد فتحي',
  'عبد الوهاب المسيري',
  'عبد الله العلايل',
  'محمد جمال الدين',
  'أحمد حسين',
  'علي الوردي',
  'حسين مروة',
  'مهدي عامل',
  'عبد العزيز الدوري',
  'جورج طرابيشي',
  'محمد عابد الجابري',
  'عبد الله العروي',
  'محمد أركون',
  'نصر حامد أبو زيد',
  'حسن حنفي',
  'فؤاد زكريا',
  'زكي نجيب محمود',
  'عبد الرحمن بدوي',
  'أحمد فؤاد الأهواني',
  'إبراهيم مدكور',
  'عثمان أمين',
  'محمد لطفي جمعة',
  'طه عبد الرحمن',
  'عبد الجبار الرفاعي',
  'محمد الشرقاوي',
  'علي شريعتي',
  'مهدي بازركان',
  'محمد باقر الصدر',
  'مرتضى مطهري',
  'علي خامنئي',
  'محمد حسين فضل الله',

  // ====================== أدب (100 اسم) ======================
  'نجيب محفوظ',
  'طه حسين',
  'عباس العقاد',
  'أحمد شوقي',
  'محمود درويش',
  'غادة السمان',
  'نزار قباني',
  'جبران خليل جبران',
  'مي زيادة',
  'علي أحمد باكثير',
  'إحسان عبد القدوس',
  'يوسف إدريس',
  'توفيق الحكيم',
  'أمين معلوف',
  'عبد الرحمن منيف',
  'حنا مينه',
  'غسان كنفاني',
  'إميل حبيبي',
  'سميح القاسم',
  'توفيق يوسف عواد',
  'جبرا إبراهيم جبرا',
  'إدوارد سعيد',
  'حليم بركات',
  'ميخائيل نعيمة',
  'أمين الريحاني',
  'إلياس فرحات',
  'مارون عبود',
  'شفيق جحا',
  'سهيل إدريس',
  'ليلى بعلبكي',
  'كوليت خوري',
  'إيميلي نصر الله',
  'هدى بركات',
  'أحلام مستغانمي',
  'واسيني الأعرج',
  'الطاهر بن جلون',
  'محمد شكري',
  'عبد الله العروي',
  'محمد زفزاف',
  'عبد الكريم غلاب',
  'أحمد المديني',
  'محمد برادة',
  'بنسالم حميش',
  'لطفي الزيات',
  'يحيى حقي',
  'عبد الحكيم قاسم',
  'بهاء طاهر',
  'صنع الله إبراهيم',
  'جمال الغيطاني',
  'إبراهيم أصلان',
  'محمد البساطي',
  'مكاوي سعيد',
  'أشرف الخمايسي',
  'أحمد خالد توفيق',
  'نبيل فاروق',
  'رأفت علام',
  'محمد صادق',
  'خيري شلبي',
  'عبد الوهاب مطاوع',
  'أنيس منصور',
  'أحمد بهاء الدين',
  'محمد حسنين هيكل',
  'مصطفى أمين',
  'علي أمين',
  'إحسان عبد القدوس',
  'يوسف السباعي',
  'ثروت أباظة',
  'عبد الله الطيب',
  'الطيب صالح',
  'عبد الرحمن الأبنودي',
  'أحمد فؤاد نجم',
  'صلاح جاهين',
  'فؤاد حداد',
  'أحمد رامي',
  'بيرم التونسي',
  'محمد إبراهيم أبو سنة',
  'عبد المعطي حجازي',
  'أمل دنقل',
  'صلاح عبد الصبور',
  'أحمد عبد المعطي حجازي',
  'فاروق شوشة',
  'محمد عفيفي مطر',
  'حسن طلب',
  'سيد حجاب',
  'عبد الرحمن العشماوي',
  'محمد الثبيتي',
  'غازي القصيبي',
  'عبد الله الفيصل',
  'خالد الفيصل',
  'بدر بن عبد المحسن',
  'سعود بن عبد الله',
  'محمد العوني',
  'عبد العزيز خوجة',
  'محمد سعيد',
  'عبد الله بخيت',
  'سامي الجمعان',
  'محمد الجفري',
  'عبد الله عواد',
  'علي الدميني',
  'محمد الربيعي',
  'عبد العزيز الصائغ',
  'أحمد مطر',
  'عبد الرزاق عبد الواحد',
  'معين بسيسو',

  // ====================== كلاسيك (100 اسم) ======================
  'فيروز',
  'أم كلثوم',
  'محمد عبد الوهاب',
  'عبد الحليم حافظ',
  'فريد الأطرش',
  'صباح',
  'وديع الصافي',
  'نور الهدى',
  'نجاة الصغيرة',
  'ليلى مراد',
  'أسمهان',
  'رياض السنباطي',
  'بليغ حمدي',
  'سيد درويش',
  'زكريا أحمد',
  'محمد القصبجي',
  'محمد فوزي',
  'محمود الشريف',
  'أحمد صدقي',
  'عبد اللطيف البنا',
  'إبراهيم حمودة',
  'عبد العزيز محمود',
  'عبد الغني السيد',
  'أحمد شوقي',
  'حسين جنيد',
  'محمد عبد المطلب',
  'شكوكو',
  'عبد العزيز كساب',
  'مصطفى كامل',
  'محمد رشدي',
  'عبد العزيز فهمي',
  'محمد حمام',
  'كارم محمود',
  'عليا التونسية',
  'رجاء عبده',
  'عفاف راضي',
  'نازك',
  'سعاد محمد',
  'صباح الجزائرية',
  'بهيجة حافظ',
  'فاطمة سرحان',
  'ماري جبران',
  'نعيمة المصرية',
  'منيرة المهدية',
  'فاطمة رشدي',
  'روز اليوسف',
  'ببا عز الدين',
  'تحية كاريوكا',
  'سمية الألفي',
  'نورا',
  'هاجر حمدي',
  'عبلة كامل',
  'سناء',
  'سهير زكي',
  'نادية عزت',
  'ليلى حلمي',
  'زينات صدقي',
  'ميمي شكيب',
  'ماري منيب',
  'فردوس محمد',
  'عزيزة حلمي',
  'أمينة محمد',
  'عقيلة راتب',
  'حورية حسن',
  'رجاء يوسف',
  'زهرة العلا',
  'زوزو نبيل',
  'ناهد سمير',
  'نبيلة السيد',
  'كريمة الشريف',
  'عواطف يوسف',
  'حسناء',
  'ليلى كامل',
  'سامية جمال',
  'نادية الجندي',
  'ناهد يسري',
  'نيللي مظلوم',
  'ميرفت',
  'هالة',
  'ناهد',
  'إيمان',
  'دينا',
  'فيفي عبده',
  'لوسي',
  'شهيرة',
  'صفاء أبو السعود',
  'سناء',
  'نادية',
  'هالة',
  'ميرفت',
  'سهير',
  'سميرة',
  'رجاء',
  'عايدة',
  'كريمة',
  'سميحة',
  'أمينة',
  'سناء',
  'عزيزة',

  // ====================== خليجي (80 اسم) ======================
  'راشد الماجد',
  'ماجد المهندس',
  'عبد المجيد عبد الله',
  'حسين الجسمي',
  'طلال مداح',
  'أبو بكر سالم',
  'محمد عبده',
  'عبد الله الرويشد',
  'نبيل شعيل',
  'إبراهيم الحكمي',
  'فهد الكبيسي',
  'مطرف المطرف',
  'عبد الكريم عبد القادر',
  'علي عبد الله',
  'خالد عبد الرحمن',
  'رابح صقر',
  'محمد عمر',
  'عبد العزيز المنصور',
  'عبد اللطيف الكويتي',
  'حسن جاسم',
  'داود الكويتي',
  'سعود الراشد',
  'أحمد الجميري',
  'عيسى المرزوق',
  'أحمد الهرمي',
  'إبراهيم جمعة',
  'سلمان العماري',
  'عبد الله بالخير',
  'صادق عبد الله',
  'عباس إبراهيم',
  'محمد عبد الله الفيصل',
  'سامي هلال',
  'علي الشريف',
  'محمد البكر',
  'عبد القادر المهنا',
  'محمد الحجاب',
  'ناصر الصالح',
  'عبد الرحمن العتيبي',
  'عبد الله السبع',
  'بدر بن عبد المحسن',
  'محمد الأحمد',
  'عبد الله الفيصل',
  'خالد الفيصل',
  'سعود بن عبد الله',
  'تركي الميزاني',
  'مساعد الرشيدي',
  'مبارك المانع',
  'فايز المالكي',
  'عبد الإله السناني',
  'محمد الخويطر',
  'عبد الرحمن الخميس',
  'عبد العزيز العلي',
  'محمد القحطاني',
  'ماجد الرشيدي',
  'نواف الصباح',
  'عبد الله العلي',
  'حسين الشريف',
  'محمد الرفاعي',
  'عبد الله الغامدي',
  'سعد الفهد',
  'عبد العزيز المعجل',
  'محمد السالم',
  'عبد الله الحجي',
  'فهد الناصر',
  'بدر الغريب',
  'عبد الله القعود',
  'فهد بن سعيد',
  'محمد السهلي',
  'عبد العزيز الفهد',
  'نايف البقمي',
  'عبد الله الدوسري',
  'محمد المطيري',
  'فهد الفهد',
  'عبد العزيز الدخيل',
  'محمد الزلام',
  'عبد الله البراهيم',
  'فهد الدوسري',
  'عبد الرحمن الحمود',
  'محمد الملا',
  'عبد الله العطوي',
  'فهد العلي'
];
const GLOBAL_CELEBRITIES = [
  // ====================== رياضة (250 اسم) ======================
  'Lionel Messi',
  'Cristiano Ronaldo',
  'Kylian Mbappé',
  'Erling Haaland',
  'Neymar Jr',
  'LeBron James',
  'Stephen Curry',
  'Michael Jordan',
  'Muhammad Ali',
  'Mike Tyson',
  'Serena Williams',
  'Roger Federer',
  'Rafael Nadal',
  'Usain Bolt',
  'Michael Phelps',
  'Tiger Woods',
  'David Beckham',
  'Zinedine Zidane',
  'Ronaldinho',
  'Karim Benzema',
  'Diego Maradona',
  'Pelé',
  'Kobe Bryant',
  'Magic Johnson',
  'Larry Bird',
  'Michael Schumacher',
  'Lewis Hamilton',
  'Kevin Durant',
  'Giannis Antetokounmpo',
  'Nikola Jokić',
  'Luka Dončić',
  'Joel Embiid',
  'James Harden',
  'Russell Westbrook',
  'Chris Paul',
  'Dwyane Wade',
  'Shaquille O\'Neal',
  'Tim Duncan',
  'Kevin Garnett',
  'Dirk Nowitzki',
  'Allen Iverson',
  'Charles Barkley',
  'Karl Malone',
  'John Stockton',
  'Scottie Pippen',
  'Bill Russell',
  'Wilt Chamberlain',
  'Kareem Abdul-Jabbar',
  'Hakeem Olajuwon',
  'David Robinson',
  'Patrick Ewing',
  'Oscar Robertson',
  'Jerry West',
  'Julius Erving',
  'Isiah Thomas',
  'Steve Nash',
  'Jason Kidd',
  'Ray Allen',
  'Reggie Miller',
  'Clyde Drexler',
  'Gary Payton',
  'Dennis Rodman',
  'Tony Parker',
  'Manu Ginóbili',
  'Pau Gasol',
  'Vince Carter',
  'Tracy McGrady',
  'Grant Hill',
  'Penny Hardaway',
  'Derrick Rose',
  'Carmelo Anthony',
  'Chris Bosh',
  'Dwight Howard',
  'Kyrie Irving',
  'Klay Thompson',
  'Draymond Green',
  'Rudy Gobert',
  'Jimmy Butler',
  'Paul George',
  'Kawhi Leonard',
  'Damian Lillard',
  'Ja Morant',
  'Zion Williamson',
  'Trae Young',
  'Anthony Davis',
  'Devin Booker',
  'Jayson Tatum',
  'Jaylen Brown',
  'Donovan Mitchell',
  'Tyler Herro',
  'Bam Adebayo',
  'Jamal Murray',
  'Aaron Gordon',
  'Nikola Vučević',
  'Domantas Sabonis',
  'De\'Aaron Fox',
  'Tyrese Haliburton',
  'Cade Cunningham',
  'Evan Mobley',
  'Scottie Barnes',
  'Paolo Banchero',
  'Cristiano Ronaldo',
  'Robert Lewandowski',
  'Mohamed Salah',
  'Kevin De Bruyne',
  'Harry Kane',
  'Erling Haaland',
  'Vinícius Júnior',
  'Jude Bellingham',
  'Pedri',
  'Gavi',
  'Phil Foden',
  'Bukayo Saka',
  'Marcus Rashford',
  'Bruno Fernandes',
  'Casemiro',
  'Rodri',
  'Rúben Dias',
  'Virgil van Dijk',
  'Alisson Becker',
  'Thibaut Courtois',
  'Manuel Neuer',
  'Jan Oblak',
  'Ederson',
  'Mike Maignan',
  'Marc-André ter Stegen',
  'Antoine Griezmann',
  'Kylian Mbappé',
  'Neymar Jr',
  'Lionel Messi',
  'Karim Benzema',
  'Luis Suárez',
  'Sergio Agüero',
  'Sergio Ramos',
  'Giorgio Chiellini',
  'Leonardo Bonucci',
  'Mats Hummels',
  'Jérôme Boateng',
  'Philipp Lahm',
  'Xavi Hernández',
  'Andrés Iniesta',
  'Iker Casillas',
  'Carles Puyol',
  'Gerard Piqué',
  'Dani Alves',
  'Marcelo',
  'Roberto Carlos',
  'Cafu',
  'Rivaldo',
  'Rivaldo',
  'Ronaldo Nazário',
  'Romário',
  'Bebeto',
  'Zico',
  'Sócrates',
  'Falcão',
  'Garrincha',
  'Johan Cruyff',
  'Franz Beckenbauer',
  'Gerd Müller',
  'Lothar Matthäus',
  'Oliver Kahn',
  'Jürgen Klopp',
  'Pep Guardiola',
  'Carlo Ancelotti',
  'José Mourinho',
  'Alex Ferguson',
  'Arsène Wenger',
  'Zinedine Zidane',
  'Michel Platini',
  'Raymond Kopa',
  'Just Fontaine',
  'Thierry Henry',
  'Patrick Vieira',
  'Claude Makélélé',
  'Lilian Thuram',
  'Laurent Blanc',
  'Didier Deschamps',
  'Fabien Barthez',
  'George Weah',
  'Samuel Eto\'o',
  'Didier Drogba',
  'Yaya Touré',
  'Sadio Mané',
  'Riyad Mahrez',
  'Achraf Hakimi',
  'Hakim Ziyech',
  'Andriy Shevchenko',
  'Oleksandr Zinchenko',
  'Mykhailo Mudryk',
  'Tiger Woods',
  'Jack Nicklaus',
  'Arnold Palmer',
  'Gary Player',
  'Rory McIlroy',
  'Jordan Spieth',
  'Brooks Koepka',
  'Dustin Johnson',
  'Phil Mickelson',
  'Tom Brady',
  'Patrick Mahomes',
  'Aaron Rodgers',
  'Joe Montana',
  'Jerry Rice',
  'Jim Brown',
  'Barry Sanders',
  'Walter Payton',
  'Lawrence Taylor',
  'Reggie White',
  'Ray Lewis',
  'Peyton Manning',
  'Drew Brees',
  'Brett Favre',
  'Dan Marino',
  'John Elway',
  'Terry Bradshaw',
  'Steve Young',
  'Kurt Warner',
  'Ben Roethlisberger',
  'Eli Manning',
  'Michael Vick',
  'Deion Sanders',
  'Primož Roglič',
  'Tadej Pogačar',
  'Jonas Vingegaard',
  'Mark Cavendish',
  'Peter Sagan',
  'Chris Froome',
  'Alberto Contador',
  'Lance Armstrong',
  'Miguel Induráin',
  'Bernard Hinault',
  'Eddy Merckx',
  'Fausto Coppi',
  'Gino Bartali',
  'Usain Bolt',
  'Carl Lewis',
  'Jesse Owens',
  'Michael Johnson',
  'Florence Griffith-Joyner',
  'Jackie Joyner-Kersee',
  'Daley Thompson',
  'Sebastian Coe',
  'Steve Ovett',
  'Haile Gebrselassie',
  'Kenenisa Bekele',
  'Eliud Kipchoge',
  'Mo Farah',
  'Michael Phelps',
  'Mark Spitz',
  'Ian Thorpe',
  'Katie Ledecky',
  'Simone Biles',
  'Nadia Comăneci',
  'Kohei Uchimura',
  'Serena Williams',
  'Venus Williams',
  'Roger Federer',
  'Rafael Nadal',
  'Novak Djokovic',
  'Andy Murray',
  'Pete Sampras',
  'Andre Agassi',
  'Björn Borg',
  'John McEnroe',
  'Jimmy Connors',
  'Ivan Lendl',
  'Stefan Edberg',
  'Boris Becker',
  'Rod Laver',
  'Martina Navratilova',
  'Steffi Graf',
  'Chris Evert',
  'Monica Seles',
  'Billie Jean King',
  'Muhammad Ali',
  'Mike Tyson',
  'Joe Frazier',
  'George Foreman',
  'Evander Holyfield',
  'Lennox Lewis',
  'Sugar Ray Robinson',
  'Sugar Ray Leonard',
  'Marvin Hagler',
  'Thomas Hearns',
  'Roberto Durán',
  'Oscar De La Hoya',
  'Manny Pacquiao',
  'Floyd Mayweather Jr',
  'Conor McGregor',
  'Jon Jones',
  'Khabib Nurmagomedov',
  'Israel Adesanya',
  'Daniel Cormier',
  'Stipe Miocic',
  'Amanda Nunes',
  'Ronda Rousey',
  'Michael Schumacher',
  'Lewis Hamilton',
  'Ayrton Senna',
  'Alain Prost',
  'Niki Lauda',
  'Jim Clark',
  'Juan Manuel Fangio',
  'Sebastian Vettel',
  'Max Verstappen',
  'Fernando Alonso',
  'Kimi Räikkönen',
  'Jenson Button',
  'Nico Rosberg',
  'Dale Earnhardt',
  'Richard Petty',
  'Jeff Gordon',
  'Jimmie Johnson',
  'Tony Stewart',
  'Mario Andretti',
  'Valentino Rossi',
  'Marc Márquez',
  'Giacomo Agostini',

  // ====================== فن (350 اسم) ======================
  'Leonardo DiCaprio',
  'Tom Holland',
  'Brad Pitt',
  'Johnny Depp',
  'Robert Downey Jr',
  'Will Smith',
  'Denzel Washington',
  'Morgan Freeman',
  'Al Pacino',
  'Scarlett Johansson',
  'Angelina Jolie',
  'Jennifer Lawrence',
  'Meryl Streep',
  'Julia Roberts',
  'Taylor Swift',
  'Michael Jackson',
  'Selena Gomez',
  'Ariana Grande',
  'Beyoncé',
  'Rihanna',
  'Lady Gaga',
  'Ed Sheeran',
  'Justin Bieber',
  'Drake',
  'The Weeknd',
  'Eminem',
  'Shakira',
  'Jennifer Lopez',
  'Madonna',
  'Whitney Houston',
  'Freddie Mercury',
  'Elvis Presley',
  'Frank Sinatra',
  'Tom Cruise',
  'Robert De Niro',
  'Jack Nicholson',
  'Dustin Hoffman',
  'Harrison Ford',
  'Clint Eastwood',
  'Samuel L. Jackson',
  'Bruce Willis',
  'Arnold Schwarzenegger',
  'Sylvester Stallone',
  'Keanu Reeves',
  'Matt Damon',
  'Ben Affleck',
  'Christian Bale',
  'Heath Ledger',
  'Joaquin Phoenix',
  'Ryan Gosling',
  'Chris Evans',
  'Chris Hemsworth',
  'Chris Pratt',
  'Mark Ruffalo',
  'Jeremy Renner',
  'Paul Rudd',
  'Don Cheadle',
  'Chadwick Boseman',
  'Michael B. Jordan',
  'Idris Elba',
  'Daniel Craig',
  'Hugh Jackman',
  'Ryan Reynolds',
  'Adam Sandler',
  'Jim Carrey',
  'Eddie Murphy',
  'Will Ferrell',
  'Kevin Hart',
  'Dwayne Johnson',
  'Jason Statham',
  'Vin Diesel',
  'John Cena',
  'Dave Bautista',
  'Michelle Rodriguez',
  'Gal Gadot',
  'Margot Robbie',
  'Emma Stone',
  'Emma Watson',
  'Natalie Portman',
  'Anne Hathaway',
  'Jessica Chastain',
  'Amy Adams',
  'Cate Blanchett',
  'Nicole Kidman',
  'Reese Witherspoon',
  'Sandra Bullock',
  'Halle Berry',
  'Charlize Theron',
  'Cameron Diaz',
  'Drew Barrymore',
  'Kate Winslet',
  'Keira Knightley',
  'Rachel McAdams',
  'Blake Lively',
  'Jennifer Aniston',
  'Courteney Cox',
  'Lisa Kudrow',
  'Matthew Perry',
  'David Schwimmer',
  'Matt LeBlanc',
  'Zendaya',
  'Timothée Chalamet',
  'Florence Pugh',
  'Anya Taylor-Joy',
  'Sydney Sweeney',
  'Millie Bobby Brown',
  'Finn Wolfhard',
  'Noah Schnapp',
  'Sadie Sink',
  'Gaten Matarazzo',
  'Caleb McLaughlin',
  'Priyanka Chopra',
  'Deepika Padukone',
  'Shah Rukh Khan',
  'Salman Khan',
  'Aamir Khan',
  'Ranbir Kapoor',
  'Ranveer Singh',
  'Alia Bhatt',
  'Katrina Kaif',
  'Kareena Kapoor',
  'BTS',
  'RM',
  'Jin',
  'SUGA',
  'j-hope',
  'Jimin',
  'V',
  'Jungkook',
  'BLACKPINK',
  'Jennie',
  'Lisa',
  'Jisoo',
  'Rosé',
  'Adele',
  'Bruno Mars',
  'Katy Perry',
  'Lady Gaga',
  'Billie Eilish',
  'Olivia Rodrigo',
  'Dua Lipa',
  'Lana Del Rey',
  'Halsey',
  'Camila Cabello',
  'Shawn Mendes',
  'Charlie Puth',
  'Harry Styles',
  'Niall Horan',
  'Liam Payne',
  'Louis Tomlinson',
  'Zayn Malik',
  'Kanye West',
  'Jay-Z',
  'Kendrick Lamar',
  'Travis Scott',
  'Post Malone',
  'Future',
  'Young Thug',
  'Gunna',
  'Lil Baby',
  'Drake',
  'Nicki Minaj',
  'Cardi B',
  'Megan Thee Stallion',
  'Doja Cat',
  'Ice Spice',
  'Mariah Carey',
  'Celine Dion',
  'Barbra Streisand',
  'Aretha Franklin',
  'Diana Ross',
  'Stevie Wonder',
  'Ray Charles',
  'James Brown',
  'Prince',
  'David Bowie',
  'Mick Jagger',
  'Keith Richards',
  'Paul McCartney',
  'John Lennon',
  'George Harrison',
  'Ringo Starr',
  'Bob Dylan',
  'Bob Marley',
  'Jim Morrison',
  'Kurt Cobain',
  'Chris Cornell',
  'Eddie Vedder',
  'Thom Yorke',
  'Bono',
  'Axl Rose',
  'Slash',
  'Jimmy Page',
  'Eric Clapton',
  'Jimi Hendrix',
  'Carlos Santana',
  'Quentin Tarantino',
  'Steven Spielberg',
  'Martin Scorsese',
  'James Cameron',
  'Christopher Nolan',
  'Peter Jackson',
  'Ridley Scott',
  'Francis Ford Coppola',
  'Stanley Kubrick',
  'Alfred Hitchcock',
  'Charlie Chaplin',
  'Buster Keaton',
  'Marilyn Monroe',
  'Audrey Hepburn',
  'Grace Kelly',
  'James Dean',
  'Marlon Brando',
  'Paul Newman',
  'Steve McQueen',
  'Gene Kelly',
  'Fred Astaire',
  'Gregory Peck',
  'Cary Grant',
  'Humphrey Bogart',
  'Ingrid Bergman',
  'Sophia Loren',
  'Elizabeth Taylor',
  'Vivien Leigh',
  'Clark Gable',
  'James Stewart',
  'Henry Fonda',
  'Katharine Hepburn',
  'Bette Davis',
  'Joan Crawford',
  'Greta Garbo',
  'John Wayne',
  'Gary Cooper',
  'Spencer Tracy',
  'Laurence Olivier',
  'Peter O\'Toole',
  'Richard Burton',
  'Sean Connery',
  'Roger Moore',
  'Timothy Dalton',
  'Pierce Brosnan',
  'George Lazenby',
  'Anthony Hopkins',
  'Ian McKellen',
  'Patrick Stewart',
  'Michael Caine',
  'Maggie Smith',
  'Judi Dench',
  'Helen Mirren',
  'Claire Foy',
  'Olivia Colman',
  'Emma Thompson',
  'Kate Beckinsale',
  'Rosamund Pike',
  'Carey Mulligan',
  'Saoirse Ronan',
  'Lupita Nyong\'o',
  'Viola Davis',
  'Octavia Spencer',
  'Mahershala Ali',
  'Rami Malek',
  'Lakeith Stanfield',
  'Daniel Kaluuya',
  'John Boyega',
  'Donald Glover',
  'Childish Gambino',
  'Tyler, The Creator',
  'Frank Ocean',
  'SZA',
  'Summer Walker',
  'Jhené Aiko',
  'H.E.R.',
  'Ella Mai',
  'Jessie Reyez',
  'Tate McRae',
  'Sabrina Carpenter',
  'Madison Beer',
  'Addison Rae',
  'Charli D\'Amelio',
  'Dixie D\'Amelio',

  // ====================== علم وتكنولوجيا وأعمال (150 اسم) ======================
  'Albert Einstein',
  'Elon Musk',
  'Isaac Newton',
  'Nikola Tesla',
  'Stephen Hawking',
  'Marie Curie',
  'Galileo Galilei',
  'Charles Darwin',
  'Bill Gates',
  'Steve Jobs',
  'Mark Zuckerberg',
  'Jeff Bezos',
  'Larry Page',
  'Sergey Brin',
  'Tim Cook',
  'Satya Nadella',
  'Sundar Pichai',
  'Jack Ma',
  'Warren Buffett',
  'Bernard Arnault',
  'Sam Altman',
  'Jensen Huang',
  'Larry Ellison',
  'Michael Dell',
  'Jeff Bezos',
  'Elon Musk',
  'Richard Branson',
  'Peter Thiel',
  'Reid Hoffman',
  'Marc Andreessen',
  'Ben Horowitz',
  'Vinod Khosla',
  'Chamath Palihapitiya',
  'Aristotle',
  'Socrates',
  'Plato',
  'Pythagoras',
  'Archimedes',
  'Euclid',
  'Ptolemy',
  'Copernicus',
  'Johannes Kepler',
  'Galileo Galilei',
  'Tycho Brahe',
  'Isaac Newton',
  'Gottfried Leibniz',
  'Pierre-Simon Laplace',
  'Joseph-Louis Lagrange',
  'Leonhard Euler',
  'Carl Friedrich Gauss',
  'Bernhard Riemann',
  'Alan Turing',
  'John von Neumann',
  'Claude Shannon',
  'Richard Feynman',
  'Niels Bohr',
  'Werner Heisenberg',
  'Erwin Schrödinger',
  'Max Planck',
  'Enrico Fermi',
  'Paul Dirac',
  'James Clerk Maxwell',
  'Michael Faraday',
  'Alessandro Volta',
  'André-Marie Ampère',
  'Georg Ohm',
  'Nikola Tesla',
  'Thomas Edison',
  'Alexander Graham Bell',
  'Guglielmo Marconi',
  'John Logie Baird',
  'Tim Berners-Lee',
  'Vint Cerf',
  'Robert Kahn',
  'Larry Roberts',
  'Ray Tomlinson',
  'Steve Wozniak',
  'Steve Jobs',
  'Bill Gates',
  'Paul Allen',
  'Mark Zuckerberg',
  'Dustin Moskovitz',
  'Eduardo Saverin',
  'Jack Dorsey',
  'Evan Williams',
  'Biz Stone',
  'Kevin Systrom',
  'Mike Krieger',
  'Jan Koum',
  'Brian Acton',
  'Daniel Ek',
  'Martin Lorentzon',
  'Reed Hastings',
  'Marc Randolph',
  'Jeff Bezos',
  'Andy Jassy',
  'Larry Page',
  'Sergey Brin',
  'Eric Schmidt',
  'Tim Cook',
  'Jonathan Ive',
  'Satya Nadella',
  'Bill Gates',
  'Melinda Gates',
  'Warren Buffett',
  'Charlie Munger',
  'Ray Dalio',
  'George Soros',
  'Carl Icahn',
  'Peter Lynch',
  'Benjamin Graham',
  'John Bogle',
  'Jack Bogle',
  'Sam Walton',
  'Jim Walton',
  'Alice Walton',
  'Rob Walton',
  'Charles Koch',
  'David Koch',
  'Michael Bloomberg',
  'Rupert Murdoch',
  'Lakshmi Mittal',
  'Mukesh Ambani',
  'Gautam Adani',
  'Tata Group',
  'Ratan Tata',
  'Carlos Slim',
  'Amancio Ortega',
  'François Pinault',
  'Bernard Arnault',
  'François-Henri Pinault',
  'Johann Rupert',
  'Elon Musk',
  'Jeff Bezos',
  'Mark Zuckerberg',
  'Bill Gates',
  'Larry Page',
  'Sergey Brin',
  'Steve Ballmer',
  'Michael Dell',
  'Larry Ellison',
  'Safra Catz',
  'Mark Hurd',
  'John Chambers',
  'Cisco',
  'Chuck Robbins',
  'IBM',
  'Arvind Krishna',
  'Intel',
  'Pat Gelsinger',
  'AMD',
  'Lisa Su',
  'NVIDIA',
  'Jensen Huang',
  'Qualcomm',
  'Cristiano Amon',
  'Broadcom',
  'Hock Tan',
  'TSMC',
  'Morris Chang',
  'Samsung',
  'Lee Jae-yong',
  'Sony',
  'Kenichiro Yoshida',
  'Microsoft',
  'Apple',
  'Google',
  'Amazon',
  'Meta',
  'Tesla',
  'SpaceX',
  'OpenAI',
  'DeepMind',
  'Demis Hassabis',
  'Mustafa Suleyman',
  'Geoffrey Hinton',
  'Yann LeCun',
  'Yoshua Bengio',
  'Andrew Ng',
  'Fei-Fei Li',
  'Ian Goodfellow',
  'Andrej Karpathy',
  'Ilya Sutskever',
  'Alex Krizhevsky',
  'Jeff Dean',
  'Sanjay Ghemawat',
  'Urs Hölzle',
  'Sebastian Thrun',
  'Peter Norvig',
  'Stuart Russell',
  'Marvin Minsky',
  'John McCarthy',
  'Alan Turing',
  'Grace Hopper',
  'Ada Lovelace',
  'Charles Babbage',
  'Blaise Pascal',
  'Gottfried Leibniz',

  // ====================== أدب وفلسفة (100 اسم) ======================
  'William Shakespeare',
  'Charles Dickens',
  'Ernest Hemingway',
  'George Orwell',
  'Jane Austen',
  'Leo Tolstoy',
  'Fyodor Dostoevsky',
  'Plato',
  'Aristotle',
  'Socrates',
  'Friedrich Nietzsche',
  'Immanuel Kant',
  'Arthur Schopenhauer',
  'Jean-Paul Sartre',
  'Albert Camus',
  'Simone de Beauvoir',
  'Michel Foucault',
  'Jacques Derrida',
  'Martin Heidegger',
  'Ludwig Wittgenstein',
  'Bertrand Russell',
  'John Stuart Mill',
  'David Hume',
  'John Locke',
  'René Descartes',
  'Baruch Spinoza',
  'Gottfried Leibniz',
  'Thomas Hobbes',
  'Jean-Jacques Rousseau',
  'Voltaire',
  'Montesquieu',
  'Karl Marx',
  'Friedrich Engels',
  'Adam Smith',
  'John Maynard Keynes',
  'Milton Friedman',
  'Friedrich Hayek',
  'Karl Popper',
  'Thomas Kuhn',
  'Noam Chomsky',
  'Mark Twain',
  'Edgar Allan Poe',
  'Herman Melville',
  'Nathaniel Hawthorne',
  'Walt Whitman',
  'Emily Dickinson',
  'F. Scott Fitzgerald',
  'William Faulkner',
  'John Steinbeck',
  'J.D. Salinger',
  'Harper Lee',
  'Toni Morrison',
  'James Baldwin',
  'Maya Angelou',
  'Ralph Ellison',
  'Jack Kerouac',
  'Allen Ginsberg',
  'Sylvia Plath',
  'Robert Frost',
  'T.S. Eliot',
  'Ezra Pound',
  'James Joyce',
  'Samuel Beckett',
  'Oscar Wilde',
  'George Bernard Shaw',
  'Virginia Woolf',
  'D.H. Lawrence',
  'Aldous Huxley',
  'George Eliot',
  'Charlotte Brontë',
  'Emily Brontë',
  'Anne Brontë',
  'Thomas Hardy',
  'Joseph Conrad',
  'E.M. Forster',
  'Graham Greene',
  'Kazuo Ishiguro',
  'Salman Rushdie',
  'Zadie Smith',
  'Ian McEwan',
  'Julian Barnes',
  'Martin Amis',
  'Margaret Atwood',
  'Alice Munro',
  'Gabriel García Márquez',
  'Jorge Luis Borges',
  'Mario Vargas Llosa',
  'Isabel Allende',
  'Julio Cortázar',
  'Pablo Neruda',
  'Octavio Paz',
  'Carlos Fuentes',
  'Miguel de Cervantes',
  'Federico García Lorca',
  'Antonio Machado',
  'Dante Alighieri',
  'Petrarch',
  'Giovanni Boccaccio',
  'Victor Hugo',
  'Alexandre Dumas',
  'Gustave Flaubert',
  'Marcel Proust',
  'Albert Camus',
  'Jean-Paul Sartre',
  'Franz Kafka',
  'Milan Kundera',
  'Rainer Maria Rilke',
  'Hermann Hesse',
  'Thomas Mann',
  'Johann Wolfgang von Goethe',
  'Friedrich Schiller',
  'Heinrich Heine',
  'Hans Christian Andersen',
  'Henrik Ibsen',
  'August Strindberg',
  'Anton Chekhov',
  'Alexander Pushkin',
  'Nikolai Gogol',
  'Ivan Turgenev',
  'Mikhail Bulgakov',
  'Boris Pasternak',
  'Aleksandr Solzhenitsyn',
  'Vladimir Nabokov',
  'Joseph Brodsky',
  'C.S. Lewis',
  'J.R.R. Tolkien',
  'George R.R. Martin',
  'J.K. Rowling',
  'Stephen King',
  'Dan Brown',
  'Paulo Coelho',
  'Haruki Murakami',
  'Orhan Pamuk',
  'Elif Shafak',
  'Chimamanda Ngozi Adichie',
  'Naguib Mahfouz',

  // ====================== كلاسيك (100 اسم) ======================
  'Charlie Chaplin',
  'Marilyn Monroe',
  'Audrey Hepburn',
  'James Dean',
  'Marlon Brando',
  'Cary Grant',
  'Grace Kelly',
  'Frank Sinatra',
  'Elvis Presley',
  'John F. Kennedy',
  'Judy Garland',
  'Gene Kelly',
  'Fred Astaire',
  'Ginger Rogers',
  'Humphrey Bogart',
  'Ingrid Bergman',
  'Lauren Bacall',
  'Katharine Hepburn',
  'Spencer Tracy',
  'Clark Gable',
  'Vivien Leigh',
  'Elizabeth Taylor',
  'Richard Burton',
  'Paul Newman',
  'Joanne Woodward',
  'Robert Redford',
  'Jane Fonda',
  'Henry Fonda',
  'James Stewart',
  'Gregory Peck',
  'Bette Davis',
  'Joan Crawford',
  'Greta Garbo',
  'Marlene Dietrich',
  'Rita Hayworth',
  'Ava Gardner',
  'Lana Turner',
  'Sophia Loren',
  'Marcello Mastroianni',
  'Federico Fellini',
  'Ingmar Bergman',
  'Akira Kurosawa',
  'Alfred Hitchcock',
  'Billy Wilder',
  'Howard Hawks',
  'John Ford',
  'Frank Capra',
  'Orson Welles',
  'Cecil B. DeMille',
  'David Lean',
  'Stanley Kubrick',
  'Francis Ford Coppola',
  'Martin Scorsese',
  'Steven Spielberg',
  'George Lucas',
  'Woody Allen',
  'Meryl Streep',
  'Robert De Niro',
  'Al Pacino',
  'Dustin Hoffman',
  'Jack Nicholson',
  'Morgan Freeman',
  'Clint Eastwood',
  'Harrison Ford',
  'Michael Caine',
  'Sean Connery',
  'Roger Moore',
  'Christopher Reeve',
  'Marlon Brando',
  'Alfred Hitchcock',
  'Charlie Chaplin',
  'Buster Keaton',
  'Harold Lloyd',
  'Stan Laurel',
  'Oliver Hardy',
  'The Marx Brothers',
  'Groucho Marx',
  'W.C. Fields',
  'Mae West',
  'Bob Hope',
  'Bing Crosby',
  'Dean Martin',
  'Jerry Lewis',
  'Sammy Davis Jr.',
  'Frank Sinatra',
  'Dean Martin',
  'Peter Lawford',
  'Joey Bishop',
  'Shirley Temple',
  'Mickey Rooney',
  'Judy Garland',
  'Debbie Reynolds',
  'Gene Kelly',
  'Donald O\'Connor',
  'Cyd Charisse',
  'Ann Miller',
  'Ginger Rogers',
  'Fred Astaire',
  'Eleanor Powell',
  'Bill Robinson',
  'Nicholas Brothers',
  'Josephine Baker',
  'Eddie Cantor',
  'Al Jolson',
  'Louis Armstrong',
  'Duke Ellington',
  'Count Basie',
  'Benny Goodman',
  'Glenn Miller',
  'Artie Shaw',
  'Tommy Dorsey',
  'Jimmy Dorsey',
  'Cab Calloway',
  'Ella Fitzgerald',
  'Billie Holiday',
  'Sarah Vaughan',
  'Dinah Washington',
  'Lena Horne',
  'Nat King Cole',
  'Tony Bennett',
  'Perry Como',
  'Andy Williams',
  'Johnny Mathis',
  'Sam Cooke',
  'Otis Redding',
  'Marvin Gaye',
  'Stevie Wonder',
  'Ray Charles',
  'James Brown',
  'Aretha Franklin',
  'The Supremes',
  'Diana Ross',
  'The Temptations',
  'The Four Tops',
  'Smokey Robinson',
  'The Miracles',
  'The Jackson 5',
  'Michael Jackson',
  'Janet Jackson',
  'Whitney Houston',
  'Mariah Carey',
  'Celine Dion',
  'Barbra Streisand',
  'Cher',
  'Tina Turner',
  'Madonna',
  'Prince',
  'David Bowie',
  'Queen',
  'Freddie Mercury',
  'The Beatles',
  'John Lennon',
  'Paul McCartney',
  'George Harrison',
  'Ringo Starr',
  'The Rolling Stones',
  'Mick Jagger',
  'Keith Richards',
  'The Who',
  'Pete Townshend',
  'Roger Daltrey',
  'Led Zeppelin',
  'Robert Plant',
  'Jimmy Page',
  'Pink Floyd',
  'David Gilmour',
  'Roger Waters',
  'The Doors',
  'Jim Morrison',
  'Nirvana',
  'Kurt Cobain',
  'Bob Dylan',
  'Jimi Hendrix',
  'Janis Joplin',
  'Jim Morrison',
  'Jimmy Hendrix',
  'Eric Clapton',
  'Jeff Beck',
  'Carlos Santana',
  'B.B. King',
  'Muddy Waters',
  'Howlin\' Wolf',
  'John Lee Hooker',
  'Buddy Holly',
  'Ritchie Valens',
  'Eddie Cochran',
  'Chuck Berry',
  'Little Richard',
  'Fats Domino',
  'Jerry Lee Lewis',
  'Roy Orbison',
  'Johnny Cash',
  'Willie Nelson',
  'Waylon Jennings',
  'Kris Kristofferson',
  'Merle Haggard',
  'George Jones',
  'Tammy Wynette',
  'Loretta Lynn',
  'Patsy Cline',
  'Dolly Parton',
  'Hank Williams',
  'Jimmie Rodgers',
  'The Carter Family'
];
function makeSystemPrompt(language = 'ar') {
  return `You are an elite character guessing engine.

PRIMARY GOAL:
Guess the character in 7 to 10 questions.

STRICT RULES:
- Ask only ONE yes/no question at a time.
- Allowed answers are: yes, no, maybe, dont_know.
- Questions must be VERY SHORT.
- Arabic questions should usually be 2 to 6 words.
- English questions should usually be 2 to 8 words.
- Do not explain anything.
- Do not add extra wording.
- Return STRICT JSON only.

QUESTION QUALITY:
- Ask only high-information questions.
- Avoid weak, vague, decorative, or repetitive questions.
- Every question should eliminate many possibilities.
- Do not repeat previous questions.

STRICT THINKING ORDER:
1. real or fictional
2. gender
3. category (actor, singer, athlete, politician, scientist)
4. nationality or region
5. era or alive status

NAME RESTRICTION:
- During question mode, NEVER mention any person name.
- NEVER ask a name-based question.
- Names are allowed only in guess mode.

GUESSING RULES:
- Never guess before question ${MIN_QUESTIONS_BEFORE_GUESS}.
- You should guess between question ${MIN_QUESTIONS_BEFORE_GUESS} and ${MAX_QUESTIONS_BEFORE_GUESS}.
- Never continue beyond question ${MAX_QUESTIONS_BEFORE_GUESS} without making one guess.
- Only ONE guess at a time.

IF A GUESS IS REJECTED:
- Do NOT make another guess immediately.
- Return to question mode.
- Ask at least ${QUESTIONS_AFTER_REJECTED_GUESS} more strong questions before the next guess.
- Do not repeat rejected guesses.

KNOWN PRIORITY:
- Prefer globally famous and Arab famous people first when evidence fits.
- Arabic examples: محمد صلاح, كاظم الساهر, عادل إمام, فيروز, أم كلثوم
- Global examples: Tom Holland, Lionel Messi, Cristiano Ronaldo, Taylor Swift, Michael Jackson

LANGUAGE:
- If language is 'ar', output Arabic only.
- If language is 'en', output English only.

OUTPUT FORMAT:

Question:
{"type":"question","text":"..."}

Guess:
{"type":"guess","name":"...","confidence":0.82}`;
}

function sessionMessages(session) {
  const transcript = session.turns.length
    ? session.turns
        .map((t, index) => `Q${index + 1}: ${t.question}\nA${index + 1}: ${t.answer}`)
        .join('\n')
    : 'No questions yet.';

  const rejected = session.rejectedGuesses.length
    ? `Rejected guesses: ${session.rejectedGuesses.join(', ')}`
    : 'Rejected guesses: none';

  const afterRejectInfo = `Questions since last rejected guess: ${session.questionsSinceLastRejectedGuess}`;

  return `${transcript}\n${rejected}\n${afterRejectInfo}`;
}

function normalizeAnswer(answer) {
  const map = {
    yes: 'yes',
    no: 'no',
    maybe: 'maybe',
    dontKnow: 'dont_know',
    dont_know: 'dont_know'
  };

  return map[answer] || 'dont_know';
}

function shortFallbackQuestion(language = 'ar', turnCount = 0) {
  const ar = [
    // الهوية الأساسية
    'هل هو رجل؟',
    'هل هي امرأة؟',
    'هل هو شخص حقيقي؟',
    'هل هو شخصية خيالية؟',
    'هل هو حي؟',
    'هل هو متوفى؟',
    
    // المجال الفني
    'هل هو ممثل؟',
    'هل هي ممثلة؟',
    'هل هو مغني؟',
    'هل هي مغنية؟',
    'هل هو مخرج؟',
    'هل هو منتج؟',
    'هل هو كاتب؟',
    'هل هي كاتبة؟',
    'هل هو شاعر؟',
    'هل هو ملحن؟',
    'هل هو موسيقي؟',
    'هل هو عازف؟',
    'هل هو كوميدي؟',
    'هل هو مذيع؟',
    'هل هو إعلامي؟',
    'هل هو رابر؟',
    'هل هو عارض أزياء؟',
    
    // المجال الرياضي
    'هل هو رياضي؟',
    'هل هي رياضية؟',
    'هل هو لاعب كرة قدم؟',
    'هل هو لاعب كرة سلة؟',
    'هل هو لاعب تنس؟',
    'هل هو لاعب غولف؟',
    'هل هو ملاكم؟',
    'هل هو مصارع؟',
    'هل هو سائق فورمولا 1؟',
    'هل هو عداء؟',
    'هل هو سباح؟',
    'هل هو لاعب كرة مضرب؟',
    'هل هو حكم؟',
    'هل هو مدرب؟',
    
    // المجال العلمي والتكنولوجي
    'هل هو عالم؟',
    'هل هي عالمة؟',
    'هل هو مخترع؟',
    'هل هو مهندس؟',
    'هل هو رجل أعمال؟',
    'هل هي سيدة أعمال؟',
    'هل هو مبرمج؟',
    'هل هو ملياردير؟',
    'هل هو في مجال التكنولوجيا؟',
    'هل هو في مجال الذكاء الاصطناعي؟',
    'هل هو طبيب؟',
    'هل هو فيزيائي؟',
    'هل هو كيميائي؟',
    'هل هو فلكي؟',
    
    // المجال الأدبي والفكري
    'هل هو أديب؟',
    'هل هي أديبة؟',
    'هل هو روائي؟',
    'هل هو فيلسوف؟',
    'هل هو مفكر؟',
    'هل هو مؤرخ؟',
    'هل هو صحفي؟',
    'هل هو ناقد؟',
    'هل هو لغوي؟',
    
    // المجال السياسي والتاريخي
    'هل هو سياسي؟',
    'هل هي سياسية؟',
    'هل هو رئيس؟',
    'هل هو ملك؟',
    'هل هو زعيم؟',
    'هل هو قائد عسكري؟',
    'هل هو ثوري؟',
    'هل هو دبلوماسي؟',
    'هل هو وزير؟',
    'هل هو شخصية تاريخية؟',
    
    // المجال الديني
    'هل هو رجل دين؟',
    'هل هو شيخ؟',
    'هل هو إمام؟',
    'هل هو عالم دين؟',
    'هل هو داعية؟',
    'هل هو قديس؟',
    'هل هو نبي؟',
    
    // الجنسية والمنطقة
    'هل هو عربي؟',
    'هل هو مصري؟',
    'هل هو سعودي؟',
    'هل هو كويتي؟',
    'هل هو إماراتي؟',
    'هل هو قطري؟',
    'هل هو بحريني؟',
    'هل هو عماني؟',
    'هل هو عراقي؟',
    'هل هو أردني؟',
    'هل هو فلسطيني؟',
    'هل هو لبناني؟',
    'هل هو سوري؟',
    'هل هو مغربي؟',
    'هل هو جزائري؟',
    'هل هو تونسي؟',
    'هل هو ليبي؟',
    'هل هو سوداني؟',
    'هل هو يمني؟',
    'هل هو أمريكي؟',
    'هل هو بريطاني؟',
    'هل هو فرنسي؟',
    'هل هو ألماني؟',
    'هل هو إسباني؟',
    'هل هو إيطالي؟',
    'هل هو برازيلي؟',
    'هل هو أرجنتيني؟',
    'هل هو هندي؟',
    'هل هو صيني؟',
    'هل هو ياباني؟',
    'هل هو كوري؟',
    'هل هو أفريقي؟',
    
    // الخصائص الفنية
    'هل هو من الزمن الجميل؟',
    'هل هو من جيل التسعينات؟',
    'هل هو من الجيل الجديد؟',
    'هل هو من الكلاسيكيات؟',
    'هل هو من الخليج؟',
    'هل هو من مصر؟',
    'هل هو من لبنان؟',
    'هل هو من المغرب العربي؟',
    'هل هو من هوليوود؟',
    'هل هو من بوليوود؟',
    
    // شهرة وتأثير
    'هل هو مشهور عالمياً؟',
    'هل هو مشهور عربياً؟',
    'هل حصل على جوائز؟',
    'هل حصل على أوسكار؟',
    'هل حصل على جائزة نوبل؟',
    'هل حصل على بالون دور؟',
    'هل هو أسطورة؟',
    'هل هو أيقونة؟',
    'هل لديه معجبين كثر؟',
    'هل اسمه معروف للجميع؟',
    
    // الإنجازات
    'هل هو بطل أولمبي؟',
    'هل فاز بكأس العالم؟',
    'هل هو صاحب رقم قياسي؟',
    'هل هو أغنى شخص؟',
    'هل هو مؤسس شركة؟',
    'هل اخترع شيئاً؟',
    'هل كتب كتاباً؟',
    'هل أخرج فيلماً؟',
    'هل غنى في حفلات عالمية؟',
    
    // العلاقات
    'هل هو متزوج؟',
    'هل هو أعزب؟',
    'هل لديه أطفال؟',
    'هل هو والد؟',
    'هل هو في علاقة؟',
    
    // الخصائص الجسدية (بدون تفاصيل رقمية)
    'هل لديه لحية؟',
    'هل هو أصلع؟',
    'هل لديه شعر طويل؟',
    'هل هو نحيف؟',
    'هل هو طويل؟',
    'هل هو ممتلئ الجسم؟',
    'هل يرتدي نظارة؟',
    'هل لديه وشم؟',
    
    // أسئلة إضافية
    'هل هو مشهور في تويتر؟',
    'هل هو مشهور في إنستقرام؟',
    'هل لديه قناة يوتيوب؟',
    'هل هو ناشط؟',
    'هل هو فاعل خير؟',
    'هل هو مثير للجدل؟',
    'هل هو محبوب؟',
    'هل هو مكروه؟',
    'هل هو غني؟',
    'هل هو فقير سابقاً؟',
    'هل بدأ من الصفر؟',
    'هل لديه قصة نجاح ملهمة؟',
    'هل تعرض لأزمة؟',
    'هل اعتزل الفن؟',
    'هل اعتزل الرياضة؟',
    'هل دخل السجن؟',
    'هل هاجر من بلده؟',
    'هل يعيش في الخارج؟'
  ];

  const en = [
    // Basic identity
    'Is it male?',
    'Is it female?',
    'Is it a real person?',
    'Is it a fictional character?',
    'Is it alive?',
    'Is it deceased?',
    
    // Entertainment field
    'Is it an actor?',
    'Is it an actress?',
    'Is it a singer?',
    'Is it a female singer?',
    'Is it a director?',
    'Is it a producer?',
    'Is it a writer?',
    'Is it a female writer?',
    'Is it a poet?',
    'Is it a composer?',
    'Is it a musician?',
    'Is it an instrumentalist?',
    'Is it a comedian?',
    'Is it a broadcaster?',
    'Is it a media personality?',
    'Is it a rapper?',
    'Is it a model?',
    
    // Sports field
    'Is it an athlete?',
    'Is it a female athlete?',
    'Is it a football player?',
    'Is it a basketball player?',
    'Is it a tennis player?',
    'Is it a golfer?',
    'Is it a boxer?',
    'Is it a wrestler?',
    'Is it a Formula 1 driver?',
    'Is it a runner?',
    'Is it a swimmer?',
    'Is it a badminton player?',
    'Is it a referee?',
    'Is it a coach?',
    
    // Science and technology field
    'Is it a scientist?',
    'Is it a female scientist?',
    'Is it an inventor?',
    'Is it an engineer?',
    'Is it a businessman?',
    'Is it a businesswoman?',
    'Is it a programmer?',
    'Is it a billionaire?',
    'Is it in technology?',
    'Is it in artificial intelligence?',
    'Is it a doctor?',
    'Is it a physicist?',
    'Is it a chemist?',
    'Is it an astronomer?',
    
    // Literature and intellectual field
    'Is it a literary figure?',
    'Is it a female literary figure?',
    'Is it a novelist?',
    'Is it a philosopher?',
    'Is it an intellectual?',
    'Is it a historian?',
    'Is it a journalist?',
    'Is it a critic?',
    'Is it a linguist?',
    
    // Political and historical field
    'Is it a politician?',
    'Is it a female politician?',
    'Is it a president?',
    'Is it a king?',
    'Is it a leader?',
    'Is it a military commander?',
    'Is it a revolutionary?',
    'Is it a diplomat?',
    'Is it a minister?',
    'Is it a historical figure?',
    
    // Religious field
    'Is it a religious figure?',
    'Is it a sheikh?',
    'Is it an imam?',
    'Is it a religious scholar?',
    'Is it a preacher?',
    'Is it a saint?',
    'Is it a prophet?',
    
    // Nationality and region
    'Is it Arab?',
    'Is it Egyptian?',
    'Is it Saudi?',
    'Is it Kuwaiti?',
    'Is it Emirati?',
    'Is it Qatari?',
    'Is it Bahraini?',
    'Is it Omani?',
    'Is it Iraqi?',
    'Is it Jordanian?',
    'Is it Palestinian?',
    'Is it Lebanese?',
    'Is it Syrian?',
    'Is it Moroccan?',
    'Is it Algerian?',
    'Is it Tunisian?',
    'Is it Libyan?',
    'Is it Sudanese?',
    'Is it Yemeni?',
    'Is it American?',
    'Is it British?',
    'Is it French?',
    'Is it German?',
    'Is it Spanish?',
    'Is it Italian?',
    'Is it Brazilian?',
    'Is it Argentine?',
    'Is it Indian?',
    'Is it Chinese?',
    'Is it Japanese?',
    'Is it Korean?',
    'Is it African?',
    
    // Artistic characteristics
    'Is it from the golden age?',
    'Is it from the 90s generation?',
    'Is it from the new generation?',
    'Is it a classic?',
    'Is it from the Gulf?',
    'Is it from Egypt?',
    'Is it from Lebanon?',
    'Is it from North Africa?',
    'Is it from Hollywood?',
    'Is it from Bollywood?',
    
    // Fame and impact
    'Is it globally famous?',
    'Is it famous in the Arab world?',
    'Has it won awards?',
    'Has it won an Oscar?',
    'Has it won a Nobel Prize?',
    'Has it won a Ballon d\'Or?',
    'Is it a legend?',
    'Is it an icon?',
    'Does it have many fans?',
    'Is its name well-known to everyone?',
    
    // Achievements
    'Is it an Olympic champion?',
    'Has it won the World Cup?',
    'Does it hold a record?',
    'Is it the richest person?',
    'Is it a company founder?',
    'Did it invent something?',
    'Did it write a book?',
    'Did it direct a film?',
    'Did it perform in global concerts?',
    
    // Relationships
    'Is it married?',
    'Is it single?',
    'Does it have children?',
    'Is it a parent?',
    'Is it in a relationship?',
    
    // Physical characteristics (without numerical details)
    'Does it have a beard?',
    'Is it bald?',
    'Does it have long hair?',
    'Is it thin?',
    'Is it tall?',
    'Is it overweight?',
    'Does it wear glasses?',
    'Does it have tattoos?',
    
    // Additional questions
    'Is it famous on Twitter?',
    'Is it famous on Instagram?',
    'Does it have a YouTube channel?',
    'Is it an activist?',
    'Is it a philanthropist?',
    'Is it controversial?',
    'Is it loved?',
    'Is it hated?',
    'Is it rich?',
    'Was it poor before?',
    'Did it start from scratch?',
    'Does it have an inspiring success story?',
    'Did it go through a crisis?',
    'Did it retire from entertainment?',
    'Did it retire from sports?',
    'Was it imprisoned?',
    'Did it emigrate from its country?',
    'Does it live abroad?'
  ];

  const list = language === 'ar' ? ar : en;
  return list[Math.min(turnCount, list.length - 1)];
}

function fallbackGuessName(language = 'ar', turnCount = 0) {
  const list = language === 'ar' ? ARAB_CELEBRITIES : GLOBAL_CELEBRITIES;
  return list[turnCount % list.length];
}

function fallbackGuess(language = 'ar', turnCount = 0) {
  return {
    type: 'guess',
    name: fallbackGuessName(language, turnCount),
    confidence: 0.35
  };
}

function isQuestionTooLong(text = '', language = 'ar') {
  const words = String(text).trim().split(/\s+/).filter(Boolean);
  return language === 'ar' ? words.length > 6 : words.length > 8;
}

ممتاز! هسه أوسع isWeakQuestion بشكل كبير عشان تكتشف الأسئلة الضعيفة أو العامة أكثر:

```javascript
function isWeakQuestion(text = '') {
  const lower = String(text).toLowerCase();
  
  const weakPatterns = [
    // أسئلة عامة جداً بالعربية
    'هل هو مشهور',
    'هل هي مشهورة',
    'هل هذه الشخصية مشهورة',
    'هل هذه الشخصية معروفة',
    'هل تعرفه',
    'هل تعرفها',
    'هل تعرف هذه الشخصية',
    'هل هو معروف',
    'هل هي معروفة',
    'هل هو شخص مشهور',
    'هل هي شخصية مشهورة',
    'هل هو شخصية عامة',
    'هل هو من المشاهير',
    'هل هو معروف عالمياً',
    'هل هو معروف عربياً',
    'هل هو مشهور في العالم',
    'هل هو مشهور في الوطن العربي',
    
    // أسئلة عامة جداً بالإنجليزية
    'is it famous',
    'is this person famous',
    'is this personality famous',
    'do you know',
    'do you know this person',
    'do you know them',
    'is it well known',
    'is it well-known',
    'is it a celebrity',
    'is it a famous person',
    'is it known',
    'is this celebrity',
    'is this famous',
    'is this person well-known',
    'is it globally famous',
    'is it internationally famous',
    
    // أسئلة تكرارية أو غير مفيدة
    'هل هو انسان',
    'هل هي انسانة',
    'هل هو شخص',
    'هل هي شخصية',
    'هل هو حقيقي',
    'هل هي حقيقية',
    'is it human',
    'is it a person',
    'is it real',
    'is it a real person',
    
    // أسئلة عن التخمين
    'هل خمنت',
    'هل توقعت',
    'هل هذا صحيح',
    'هل اجابة',
    'did i guess',
    'did you guess',
    'is that correct',
    'is this right',
    'am i right',
    
    // أسئلة متكررة جداً
    'هل هو ذكر',
    'هل هي انثى',
    'هل هو رجل',
    'هل هي امرأة',
    'is it male',
    'is it female',
    'is it a man',
    'is it a woman',
    
    // أسئلة عامة عن الجنسية
    'هل هو عربي',
    'هل هي عربية',
    'is it arab',
    'is it arabic',
    'هل هو اجنبي',
    'هل هي اجنبية',
    'is it foreign',
    
    // أسئلة عامة عن المجال
    'هل هو فنان',
    'هل هي فنانة',
    'هل هو ممثل',
    'هل هي ممثلة',
    'is it an artist',
    'is it an actor',
    'is it an actress',
    'هل هو مغني',
    'هل هي مغنية',
    'is it a singer',
    'هل هو رياضي',
    'هل هي رياضية',
    'is it an athlete',
    
    // أسئلة عن الحياة والموت
    'هل هو حي',
    'هل هي حية',
    'هل هو ميت',
    'هل هي ميتة',
    'is it alive',
    'is it dead',
    'is it deceased',
    'is it living',
    
    // أسئلة فضفاضة
    'هل يمكنك',
    'هل تستطيع',
    'هل تظن',
    'هل تعتقد',
    'can you',
    'do you think',
    'do you believe',
    'what about',
    'what is',
    
    // أسئلة مكررة بأشكال مختلفة
    'هل هو',
    'هل هي',
    'هل هذا',
    'هل هذه',
    'is it',
    'is this',
    'is that',
    'are you',
    
    // أسئلة عامة جداً بدون فائدة
    'شخص',
    'person',
    'celebrity',
    'مشهور',
    'famous',
    'معروف',
    'well known'
  ];
  
 
المميزات الجديدة:

1. أكثر من 100 نمط للكشف عن الأسئلة الضعيفة
2. يغطي العربية والإنجليزية
3. يكشف الأسئلة العامة جداً مثل:
   · "هل هو مشهور؟"
   · "هل تعرفه؟"
   · "is it famous?"
   · "do you know this person?"
4. يكشف الأسئلة القصيرة جداً (أقل من 10 أحرف وتحتوي على "هل" أو "is")
5. يكشف الأسئلة التي تحتوي على كلمات عامة فقط مثل "هل هو شخص مشهور؟"
6. يصنف الأسئلة الضعيفة إلى فئات:
   · أسئلة عامة عن الشهرة
   · أسئلة مكررة
   · أسئلة عن التخمين
   · أسئلة قصيرة جداً
   · أسئلة تحتوي على كلمات عامة فقط

بهذا الشكل، اللعبة ترفض الأسئلة الضعيفة وتحفز اللاعب يسأل أسئلة أكثر تحديداً وفائدة 👌
  return weakPatterns.some((p) => lower.includes(p));
}

function looksLikeNameQuestion(text = '') {
  const lower = String(text).toLowerCase().trim();

  if (!lower) return false;

  return (
    lower.startsWith('is it ') ||
    lower.startsWith('could it be ') ||
    lower.startsWith('is this ') ||
    lower.includes('michael') ||
    lower.includes('tom ') ||
    lower.includes('messi') ||
    lower.includes('ronaldo') ||
    lower.includes('محمد') ||
    lower.includes('صلاح') ||
    lower.includes('عادل') ||
    lower.includes('هل هو ') && lower.split(/\s+/).length > 4
  );
}

function sanitizeEngineResult(result, session) {
  const turnCount = session.turns.length;

  if (!result || typeof result !== 'object') {
    return {
      type: 'question',
      text: shortFallbackQuestion(session.language, turnCount)
    };
  }

  if (result.type === 'question') {
    const text = String(result.text || '').trim();

    if (!text) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    if (isQuestionTooLong(text, session.language)) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    if (isWeakQuestion(text)) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    if (looksLikeNameQuestion(text)) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    return {
      type: 'question',
      text
    };
  }

  if (result.type === 'guess') {
    const name = String(result.name || '').trim();

    if (!name) {
      return fallbackGuess(session.language, turnCount);
    }

    if (session.rejectedGuesses.includes(name)) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    return {
      type: 'guess',
      name,
      confidence: typeof result.confidence === 'number' ? result.confidence : 0.6
    };
  }

  return {
    type: 'question',
    text: shortFallbackQuestion(session.language, turnCount)
  };
}

async function forceGuess(session) {
  if (!openai) {
    return fallbackGuess(session.language, session.turns.length);
  }

  const response = await openai.chat.completions.create({
    model,
    temperature: 0.3,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content: `Make your best single guess now.
Return STRICT JSON only.

Format:
{"type":"guess","name":"...","confidence":0.82}`
      },
      {
        role: 'user',
        content: `Language: ${session.language === 'ar' ? 'Arabic' : 'English'}

Game state:
${sessionMessages(session)}

Make the best single guess now.`
      }
    ]
  });

  const raw = response.choices[0]?.message?.content || '{}';

  try {
    const parsed = JSON.parse(raw);
    return sanitizeEngineResult(parsed, session);
  } catch {
    return fallbackGuess(session.language, session.turns.length);
  }
}

async function askEngine(session) {
  const turnCount = session.turns.length;

  const canGuessNow =
    turnCount >= MIN_QUESTIONS_BEFORE_GUESS &&
    session.questionsSinceLastRejectedGuess >= QUESTIONS_AFTER_REJECTED_GUESS;

  if (!openai) {
    const fallbackQuestions = session.language === 'ar'
      ? [
          'هل هو رجل؟',
          'هل هو حقيقي؟',
          'هل هو ممثل؟',
          'هل هو عربي؟',
          'هل هو حي؟',
          'هل هو مغني؟',
          'هل هو رياضي؟'
        ]
      : [
          'Is it male?',
          'Is it real?',
          'Is it an actor?',
          'Is it Arab?',
          'Is it alive?',
          'Is it a singer?',
          'Is it an athlete?'
        ];

    if (turnCount < MIN_QUESTIONS_BEFORE_GUESS) {
      return {
        type: 'question',
        text: fallbackQuestions[Math.min(turnCount, fallbackQuestions.length - 1)]
      };
    }

    return fallbackGuess(session.language, turnCount);
  }

  const response = await openai.chat.completions.create({
    model,
    temperature: 0.3,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: makeSystemPrompt(session.language) },
      {
        role: 'user',
        content: `Language: ${session.language === 'ar' ? 'Arabic' : 'English'}

Game state:
${sessionMessages(session)}

Server rules:
- Ask very short questions only.
- Never mention a person name during questions.
- Never guess before question ${MIN_QUESTIONS_BEFORE_GUESS}.
- Guess between question ${MIN_QUESTIONS_BEFORE_GUESS} and ${MAX_QUESTIONS_BEFORE_GUESS}.
- If a guess was rejected, ask at least ${QUESTIONS_AFTER_REJECTED_GUESS} more questions before guessing again.
- Choose the strongest narrowing question each time.`
      }
    ]
  });

  const raw = response.choices[0]?.message?.content || '{}';

  try {
    const parsed = JSON.parse(raw);
    const result = sanitizeEngineResult(parsed, session);

    if (result.type === 'guess' && !canGuessNow) {
      return {
        type: 'question',
        text: shortFallbackQuestion(session.language, turnCount)
      };
    }

    if (turnCount >= MAX_QUESTIONS_BEFORE_GUESS && result.type !== 'guess') {
      return await forceGuess(session);
    }

    return result;
  } catch {
    if (turnCount >= MAX_QUESTIONS_BEFORE_GUESS) {
      return await forceGuess(session);
    }

    return {
      type: 'question',
      text: shortFallbackQuestion(session.language, turnCount)
    };
  }
}

async function fetchWikipediaSummary(name, language = 'ar') {
  const lang = language === 'ar' ? 'ar' : 'en';
  const title = encodeURIComponent(name.replace(/ /g, '_'));
  const url = `https://${lang}.wikipedia.org/api/rest_v1/page/summary/${title}`;

  const res = await fetch(url);

  if (!res.ok) {
    return {
      title: name,
      extract: language === 'ar'
        ? 'لا توجد معلومات متاحة'
        : 'No information available',
      imageURL: null,
      articleURL: `https://${lang}.wikipedia.org/wiki/${title}`
    };
  }

  const json = await res.json();

  return {
    title: json.title || name,
    extract: json.extract || '',
    imageURL: json.thumbnail?.source || null,
    articleURL: json.content_urls?.desktop?.page || `https://${lang}.wikipedia.org/wiki/${title}`
  };
}

app.get('/api/health', (_req, res) => {
  res.json({
    ok: true,
    model,
    hasOpenAI: Boolean(openai)
  });
});

app.post('/api/game/start', async (req, res) => {
  try {
    const language = req.body?.language === 'en' ? 'en' : 'ar';
    const sessionId = crypto.randomUUID();

    const session = {
      id: sessionId,
      language,
      turns: [],
      rejectedGuesses: [],
      questionsSinceLastRejectedGuess: QUESTIONS_AFTER_REJECTED_GUESS
    };

    sessions.set(sessionId, session);

    const result = await askEngine(session);

    res.json({ sessionId, ...result });
  } catch (error) {
    console.error('/api/game/start error:', error);
    res.status(500).json({ error: 'Failed to start game' });
  }
});

app.post('/api/game/answer', async (req, res) => {
  try {
    const { sessionId, question, answer } = req.body || {};
    const session = sessions.get(sessionId);

    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    session.turns.push({
      question: String(question || ''),
      answer: normalizeAnswer(answer)
    });

    session.questionsSinceLastRejectedGuess += 1;

    const result = await askEngine(session);

    res.json(result);
  } catch (error) {
    console.error('/api/game/answer error:', error);
    res.status(500).json({ error: 'Failed to process answer' });
  }
});

app.post('/api/game/guess-confirm', async (req, res) => {
  try {
    const { sessionId, guessName, correct } = req.body || {};
    const session = sessions.get(sessionId);

    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    if (correct) {
      const wiki = await fetchWikipediaSummary(String(guessName || ''), session.language);

      return res.json({
        type: 'revealed',
        guessName,
        wiki
      });
    }

    if (guessName) {
      session.rejectedGuesses.push(String(guessName));
    }

    session.questionsSinceLastRejectedGuess = 0;

    const result = await askEngine(session);

    return res.json(result);
  } catch (error) {
    console.error('/api/game/guess-confirm error:', error);
    res.status(500).json({ error: 'Failed to confirm guess' });
  }
});

app.get('/api/wiki', async (req, res) => {
  try {
    const name = String(req.query.name || '');
    const language = req.query.language === 'en' ? 'en' : 'ar';

    if (!name) {
      return res.status(400).json({ error: 'name is required' });
    }

    const wiki = await fetchWikipediaSummary(name, language);

    res.json(wiki);
  } catch (error) {
    console.error('/api/wiki error:', error);
    res.status(500).json({ error: 'Failed to fetch wiki' });
  }
});

app.listen(port, () => {
  console.log(`Magic Ball server running on http://localhost:${port}`);
});
